"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MFI = exports.mfi = exports.VolumeProfile = exports.volumeprofile = exports.VWAP = exports.vwap = exports.AwesomeOscillator = exports.awesomeoscillator = exports.CCI = exports.cci = exports.ForceIndex = exports.forceindex = exports.TRIX = exports.trix = exports.OBV = exports.obv = exports.ADL = exports.adl = exports.WilliamsR = exports.williamsr = exports.Stochastic = exports.stochastic = exports.PSAR = exports.psar = exports.KST = exports.kst = exports.ROC = exports.roc = exports.TrueRange = exports.truerange = exports.ATR = exports.atr = exports.ADX = exports.adx = exports.BollingerBands = exports.bollingerbands = exports.RSI = exports.rsi = exports.MACD = exports.macd = exports.WEMA = exports.wema = exports.WMA = exports.wma = exports.EMA = exports.ema = exports.SMA = exports.sma = exports.CandleList = exports.CandleData = void 0;
exports.hangingman = exports.hammerpatternunconfirmed = exports.hammerpattern = exports.bearishinvertedhammerstick = exports.bullishinvertedhammerstick = exports.bearishhammerstick = exports.bullishhammerstick = exports.threewhitesoldiers = exports.threeblackcrows = exports.bearishspinningtop = exports.bullishspinningtop = exports.piercingline = exports.bearishmarubozu = exports.bullishmarubozu = exports.morningstar = exports.morningdojistar = exports.eveningstar = exports.eveningdojistar = exports.bearishharamicross = exports.bullishharamicross = exports.bearishharami = exports.bullishharami = exports.gravestonedoji = exports.dragonflydoji = exports.downsidetasukigap = exports.darkcloudcover = exports.bullishengulfingpattern = exports.bearishengulfingpattern = exports.doji = exports.abandonedbaby = exports.bearish = exports.bullish = exports.heikinashi = exports.HeikinAshi = exports.renko = exports.FixedSizeLinkedList = exports.Sum = exports.sum = exports.Lowest = exports.lowest = exports.Highest = exports.highest = exports.SD = exports.sd = exports.AverageLoss = exports.averageloss = exports.AverageGain = exports.averagegain = exports.StochasticRSI = exports.stochasticrsi = void 0;
exports.getConfig = exports.setConfig = exports.CrossDown = exports.crossDown = exports.CrossUp = exports.crossUp = exports.SupertrendOutput = exports.SupertrendInput = exports.Supertrend = exports.supertrend = exports.ChandelierExitOutput = exports.ChandelierExitInput = exports.ChandelierExit = exports.chandelierexit = exports.KeltnerChannelsOutput = exports.KeltnerChannelsInput = exports.KeltnerChannels = exports.keltnerchannels = exports.IchimokuCloud = exports.ichimokucloud = exports.fibonacciretracement = exports.tweezerbottom = exports.tweezertop = exports.shootingstarunconfirmed = exports.shootingstar = exports.hangingmanunconfirmed = void 0;
const FixedSizeLinkedList_1 = require("./Utils/FixedSizeLinkedList");
exports.FixedSizeLinkedList = FixedSizeLinkedList_1.default;
var StockData_1 = require("./StockData");
Object.defineProperty(exports, "CandleData", { enumerable: true, get: function () { return StockData_1.CandleData; } });
Object.defineProperty(exports, "CandleList", { enumerable: true, get: function () { return StockData_1.CandleList; } });
var SMA_1 = require("./moving_averages/SMA");
Object.defineProperty(exports, "sma", { enumerable: true, get: function () { return SMA_1.sma; } });
Object.defineProperty(exports, "SMA", { enumerable: true, get: function () { return SMA_1.SMA; } });
var EMA_1 = require("./moving_averages/EMA");
Object.defineProperty(exports, "ema", { enumerable: true, get: function () { return EMA_1.ema; } });
Object.defineProperty(exports, "EMA", { enumerable: true, get: function () { return EMA_1.EMA; } });
var WMA_1 = require("./moving_averages/WMA");
Object.defineProperty(exports, "wma", { enumerable: true, get: function () { return WMA_1.wma; } });
Object.defineProperty(exports, "WMA", { enumerable: true, get: function () { return WMA_1.WMA; } });
var WEMA_1 = require("./moving_averages/WEMA");
Object.defineProperty(exports, "wema", { enumerable: true, get: function () { return WEMA_1.wema; } });
Object.defineProperty(exports, "WEMA", { enumerable: true, get: function () { return WEMA_1.WEMA; } });
var MACD_1 = require("./moving_averages/MACD");
Object.defineProperty(exports, "macd", { enumerable: true, get: function () { return MACD_1.macd; } });
Object.defineProperty(exports, "MACD", { enumerable: true, get: function () { return MACD_1.MACD; } });
var RSI_1 = require("./oscillators/RSI");
Object.defineProperty(exports, "rsi", { enumerable: true, get: function () { return RSI_1.rsi; } });
Object.defineProperty(exports, "RSI", { enumerable: true, get: function () { return RSI_1.RSI; } });
var BollingerBands_1 = require("./volatility/BollingerBands");
Object.defineProperty(exports, "bollingerbands", { enumerable: true, get: function () { return BollingerBands_1.bollingerbands; } });
Object.defineProperty(exports, "BollingerBands", { enumerable: true, get: function () { return BollingerBands_1.BollingerBands; } });
var ADX_1 = require("./directionalmovement/ADX");
Object.defineProperty(exports, "adx", { enumerable: true, get: function () { return ADX_1.adx; } });
Object.defineProperty(exports, "ADX", { enumerable: true, get: function () { return ADX_1.ADX; } });
var ATR_1 = require("./directionalmovement/ATR");
Object.defineProperty(exports, "atr", { enumerable: true, get: function () { return ATR_1.atr; } });
Object.defineProperty(exports, "ATR", { enumerable: true, get: function () { return ATR_1.ATR; } });
var TrueRange_1 = require("./directionalmovement/TrueRange");
Object.defineProperty(exports, "truerange", { enumerable: true, get: function () { return TrueRange_1.truerange; } });
Object.defineProperty(exports, "TrueRange", { enumerable: true, get: function () { return TrueRange_1.TrueRange; } });
var ROC_1 = require("./momentum/ROC");
Object.defineProperty(exports, "roc", { enumerable: true, get: function () { return ROC_1.roc; } });
Object.defineProperty(exports, "ROC", { enumerable: true, get: function () { return ROC_1.ROC; } });
var KST_1 = require("./momentum/KST");
Object.defineProperty(exports, "kst", { enumerable: true, get: function () { return KST_1.kst; } });
Object.defineProperty(exports, "KST", { enumerable: true, get: function () { return KST_1.KST; } });
var PSAR_1 = require("./momentum/PSAR");
Object.defineProperty(exports, "psar", { enumerable: true, get: function () { return PSAR_1.psar; } });
Object.defineProperty(exports, "PSAR", { enumerable: true, get: function () { return PSAR_1.PSAR; } });
var Stochastic_1 = require("./momentum/Stochastic");
Object.defineProperty(exports, "stochastic", { enumerable: true, get: function () { return Stochastic_1.stochastic; } });
Object.defineProperty(exports, "Stochastic", { enumerable: true, get: function () { return Stochastic_1.Stochastic; } });
var WilliamsR_1 = require("./momentum/WilliamsR");
Object.defineProperty(exports, "williamsr", { enumerable: true, get: function () { return WilliamsR_1.williamsr; } });
Object.defineProperty(exports, "WilliamsR", { enumerable: true, get: function () { return WilliamsR_1.WilliamsR; } });
var ADL_1 = require("./volume/ADL");
Object.defineProperty(exports, "adl", { enumerable: true, get: function () { return ADL_1.adl; } });
Object.defineProperty(exports, "ADL", { enumerable: true, get: function () { return ADL_1.ADL; } });
var OBV_1 = require("./volume/OBV");
Object.defineProperty(exports, "obv", { enumerable: true, get: function () { return OBV_1.obv; } });
Object.defineProperty(exports, "OBV", { enumerable: true, get: function () { return OBV_1.OBV; } });
var TRIX_1 = require("./momentum/TRIX");
Object.defineProperty(exports, "trix", { enumerable: true, get: function () { return TRIX_1.trix; } });
Object.defineProperty(exports, "TRIX", { enumerable: true, get: function () { return TRIX_1.TRIX; } });
var ForceIndex_1 = require("./volume/ForceIndex");
Object.defineProperty(exports, "forceindex", { enumerable: true, get: function () { return ForceIndex_1.forceindex; } });
Object.defineProperty(exports, "ForceIndex", { enumerable: true, get: function () { return ForceIndex_1.ForceIndex; } });
var CCI_1 = require("./oscillators/CCI");
Object.defineProperty(exports, "cci", { enumerable: true, get: function () { return CCI_1.cci; } });
Object.defineProperty(exports, "CCI", { enumerable: true, get: function () { return CCI_1.CCI; } });
var AwesomeOscillator_1 = require("./oscillators/AwesomeOscillator");
Object.defineProperty(exports, "awesomeoscillator", { enumerable: true, get: function () { return AwesomeOscillator_1.awesomeoscillator; } });
Object.defineProperty(exports, "AwesomeOscillator", { enumerable: true, get: function () { return AwesomeOscillator_1.AwesomeOscillator; } });
var VWAP_1 = require("./volume/VWAP");
Object.defineProperty(exports, "vwap", { enumerable: true, get: function () { return VWAP_1.vwap; } });
Object.defineProperty(exports, "VWAP", { enumerable: true, get: function () { return VWAP_1.VWAP; } });
var VolumeProfile_1 = require("./volume/VolumeProfile");
Object.defineProperty(exports, "volumeprofile", { enumerable: true, get: function () { return VolumeProfile_1.volumeprofile; } });
Object.defineProperty(exports, "VolumeProfile", { enumerable: true, get: function () { return VolumeProfile_1.VolumeProfile; } });
var MFI_1 = require("./volume/MFI");
Object.defineProperty(exports, "mfi", { enumerable: true, get: function () { return MFI_1.mfi; } });
Object.defineProperty(exports, "MFI", { enumerable: true, get: function () { return MFI_1.MFI; } });
var StochasticRSI_1 = require("./momentum/StochasticRSI");
Object.defineProperty(exports, "stochasticrsi", { enumerable: true, get: function () { return StochasticRSI_1.stochasticrsi; } });
Object.defineProperty(exports, "StochasticRSI", { enumerable: true, get: function () { return StochasticRSI_1.StochasticRSI; } });
var AverageGain_1 = require("./Utils/AverageGain");
Object.defineProperty(exports, "averagegain", { enumerable: true, get: function () { return AverageGain_1.averagegain; } });
Object.defineProperty(exports, "AverageGain", { enumerable: true, get: function () { return AverageGain_1.AverageGain; } });
var AverageLoss_1 = require("./Utils/AverageLoss");
Object.defineProperty(exports, "averageloss", { enumerable: true, get: function () { return AverageLoss_1.averageloss; } });
Object.defineProperty(exports, "AverageLoss", { enumerable: true, get: function () { return AverageLoss_1.AverageLoss; } });
var SD_1 = require("./Utils/SD");
Object.defineProperty(exports, "sd", { enumerable: true, get: function () { return SD_1.sd; } });
Object.defineProperty(exports, "SD", { enumerable: true, get: function () { return SD_1.SD; } });
var Highest_1 = require("./Utils/Highest");
Object.defineProperty(exports, "highest", { enumerable: true, get: function () { return Highest_1.highest; } });
Object.defineProperty(exports, "Highest", { enumerable: true, get: function () { return Highest_1.Highest; } });
var Lowest_1 = require("./Utils/Lowest");
Object.defineProperty(exports, "lowest", { enumerable: true, get: function () { return Lowest_1.lowest; } });
Object.defineProperty(exports, "Lowest", { enumerable: true, get: function () { return Lowest_1.Lowest; } });
var Sum_1 = require("./Utils/Sum");
Object.defineProperty(exports, "sum", { enumerable: true, get: function () { return Sum_1.sum; } });
Object.defineProperty(exports, "Sum", { enumerable: true, get: function () { return Sum_1.Sum; } });
var Renko_1 = require("./chart_types/Renko");
Object.defineProperty(exports, "renko", { enumerable: true, get: function () { return Renko_1.renko; } });
var HeikinAshi_1 = require("./chart_types/HeikinAshi");
Object.defineProperty(exports, "HeikinAshi", { enumerable: true, get: function () { return HeikinAshi_1.HeikinAshi; } });
Object.defineProperty(exports, "heikinashi", { enumerable: true, get: function () { return HeikinAshi_1.heikinashi; } });
var Bullish_1 = require("./candlestick/Bullish");
Object.defineProperty(exports, "bullish", { enumerable: true, get: function () { return Bullish_1.bullish; } });
var Bearish_1 = require("./candlestick/Bearish");
Object.defineProperty(exports, "bearish", { enumerable: true, get: function () { return Bearish_1.bearish; } });
var AbandonedBaby_1 = require("./candlestick/AbandonedBaby");
Object.defineProperty(exports, "abandonedbaby", { enumerable: true, get: function () { return AbandonedBaby_1.abandonedbaby; } });
var Doji_1 = require("./candlestick/Doji");
Object.defineProperty(exports, "doji", { enumerable: true, get: function () { return Doji_1.doji; } });
var BearishEngulfingPattern_1 = require("./candlestick/BearishEngulfingPattern");
Object.defineProperty(exports, "bearishengulfingpattern", { enumerable: true, get: function () { return BearishEngulfingPattern_1.bearishengulfingpattern; } });
var BullishEngulfingPattern_1 = require("./candlestick/BullishEngulfingPattern");
Object.defineProperty(exports, "bullishengulfingpattern", { enumerable: true, get: function () { return BullishEngulfingPattern_1.bullishengulfingpattern; } });
var DarkCloudCover_1 = require("./candlestick/DarkCloudCover");
Object.defineProperty(exports, "darkcloudcover", { enumerable: true, get: function () { return DarkCloudCover_1.darkcloudcover; } });
var DownsideTasukiGap_1 = require("./candlestick/DownsideTasukiGap");
Object.defineProperty(exports, "downsidetasukigap", { enumerable: true, get: function () { return DownsideTasukiGap_1.downsidetasukigap; } });
var DragonFlyDoji_1 = require("./candlestick/DragonFlyDoji");
Object.defineProperty(exports, "dragonflydoji", { enumerable: true, get: function () { return DragonFlyDoji_1.dragonflydoji; } });
var GraveStoneDoji_1 = require("./candlestick/GraveStoneDoji");
Object.defineProperty(exports, "gravestonedoji", { enumerable: true, get: function () { return GraveStoneDoji_1.gravestonedoji; } });
var BullishHarami_1 = require("./candlestick/BullishHarami");
Object.defineProperty(exports, "bullishharami", { enumerable: true, get: function () { return BullishHarami_1.bullishharami; } });
var BearishHarami_1 = require("./candlestick/BearishHarami");
Object.defineProperty(exports, "bearishharami", { enumerable: true, get: function () { return BearishHarami_1.bearishharami; } });
var BullishHaramiCross_1 = require("./candlestick/BullishHaramiCross");
Object.defineProperty(exports, "bullishharamicross", { enumerable: true, get: function () { return BullishHaramiCross_1.bullishharamicross; } });
var BearishHaramiCross_1 = require("./candlestick/BearishHaramiCross");
Object.defineProperty(exports, "bearishharamicross", { enumerable: true, get: function () { return BearishHaramiCross_1.bearishharamicross; } });
var EveningDojiStar_1 = require("./candlestick/EveningDojiStar");
Object.defineProperty(exports, "eveningdojistar", { enumerable: true, get: function () { return EveningDojiStar_1.eveningdojistar; } });
var EveningStar_1 = require("./candlestick/EveningStar");
Object.defineProperty(exports, "eveningstar", { enumerable: true, get: function () { return EveningStar_1.eveningstar; } });
var MorningDojiStar_1 = require("./candlestick/MorningDojiStar");
Object.defineProperty(exports, "morningdojistar", { enumerable: true, get: function () { return MorningDojiStar_1.morningdojistar; } });
var MorningStar_1 = require("./candlestick/MorningStar");
Object.defineProperty(exports, "morningstar", { enumerable: true, get: function () { return MorningStar_1.morningstar; } });
var BullishMarubozu_1 = require("./candlestick/BullishMarubozu");
Object.defineProperty(exports, "bullishmarubozu", { enumerable: true, get: function () { return BullishMarubozu_1.bullishmarubozu; } });
var BearishMarubozu_1 = require("./candlestick/BearishMarubozu");
Object.defineProperty(exports, "bearishmarubozu", { enumerable: true, get: function () { return BearishMarubozu_1.bearishmarubozu; } });
var PiercingLine_1 = require("./candlestick/PiercingLine");
Object.defineProperty(exports, "piercingline", { enumerable: true, get: function () { return PiercingLine_1.piercingline; } });
var BullishSpinningTop_1 = require("./candlestick/BullishSpinningTop");
Object.defineProperty(exports, "bullishspinningtop", { enumerable: true, get: function () { return BullishSpinningTop_1.bullishspinningtop; } });
var BearishSpinningTop_1 = require("./candlestick/BearishSpinningTop");
Object.defineProperty(exports, "bearishspinningtop", { enumerable: true, get: function () { return BearishSpinningTop_1.bearishspinningtop; } });
var ThreeBlackCrows_1 = require("./candlestick/ThreeBlackCrows");
Object.defineProperty(exports, "threeblackcrows", { enumerable: true, get: function () { return ThreeBlackCrows_1.threeblackcrows; } });
var ThreeWhiteSoldiers_1 = require("./candlestick/ThreeWhiteSoldiers");
Object.defineProperty(exports, "threewhitesoldiers", { enumerable: true, get: function () { return ThreeWhiteSoldiers_1.threewhitesoldiers; } });
var BullishHammerStick_1 = require("./candlestick/BullishHammerStick");
Object.defineProperty(exports, "bullishhammerstick", { enumerable: true, get: function () { return BullishHammerStick_1.bullishhammerstick; } });
var BearishHammerStick_1 = require("./candlestick/BearishHammerStick");
Object.defineProperty(exports, "bearishhammerstick", { enumerable: true, get: function () { return BearishHammerStick_1.bearishhammerstick; } });
var BullishInvertedHammerStick_1 = require("./candlestick/BullishInvertedHammerStick");
Object.defineProperty(exports, "bullishinvertedhammerstick", { enumerable: true, get: function () { return BullishInvertedHammerStick_1.bullishinvertedhammerstick; } });
var BearishInvertedHammerStick_1 = require("./candlestick/BearishInvertedHammerStick");
Object.defineProperty(exports, "bearishinvertedhammerstick", { enumerable: true, get: function () { return BearishInvertedHammerStick_1.bearishinvertedhammerstick; } });
var HammerPattern_1 = require("./candlestick/HammerPattern");
Object.defineProperty(exports, "hammerpattern", { enumerable: true, get: function () { return HammerPattern_1.hammerpattern; } });
var HammerPatternUnconfirmed_1 = require("./candlestick/HammerPatternUnconfirmed");
Object.defineProperty(exports, "hammerpatternunconfirmed", { enumerable: true, get: function () { return HammerPatternUnconfirmed_1.hammerpatternunconfirmed; } });
var HangingMan_1 = require("./candlestick/HangingMan");
Object.defineProperty(exports, "hangingman", { enumerable: true, get: function () { return HangingMan_1.hangingman; } });
var HangingManUnconfirmed_1 = require("./candlestick/HangingManUnconfirmed");
Object.defineProperty(exports, "hangingmanunconfirmed", { enumerable: true, get: function () { return HangingManUnconfirmed_1.hangingmanunconfirmed; } });
var ShootingStar_1 = require("./candlestick/ShootingStar");
Object.defineProperty(exports, "shootingstar", { enumerable: true, get: function () { return ShootingStar_1.shootingstar; } });
var ShootingStarUnconfirmed_1 = require("./candlestick/ShootingStarUnconfirmed");
Object.defineProperty(exports, "shootingstarunconfirmed", { enumerable: true, get: function () { return ShootingStarUnconfirmed_1.shootingstarunconfirmed; } });
var TweezerTop_1 = require("./candlestick/TweezerTop");
Object.defineProperty(exports, "tweezertop", { enumerable: true, get: function () { return TweezerTop_1.tweezertop; } });
var TweezerBottom_1 = require("./candlestick/TweezerBottom");
Object.defineProperty(exports, "tweezerbottom", { enumerable: true, get: function () { return TweezerBottom_1.tweezerbottom; } });
var fibonacci_1 = require("./drawingtools/fibonacci");
Object.defineProperty(exports, "fibonacciretracement", { enumerable: true, get: function () { return fibonacci_1.fibonacciretracement; } });
// export  { predictPattern, PatternDetector }              from './patterndetection/patterndetection';
// export  { AvailablePatterns }              from './patterndetection/patterndetection';
// export  { hasDoubleBottom}              from './patterndetection/patterndetection';
// export  { hasDoubleTop }                from './patterndetection/patterndetection';
// export  { hasHeadAndShoulder}           from './patterndetection/patterndetection';
// export  { hasInverseHeadAndShoulder }   from './patterndetection/patterndetection';
// export  { isTrendingUp}                 from './patterndetection/patterndetection';
// export  { isTrendingDown }              from './patterndetection/patterndetection';
var IchimokuCloud_1 = require("./ichimoku/IchimokuCloud");
Object.defineProperty(exports, "ichimokucloud", { enumerable: true, get: function () { return IchimokuCloud_1.ichimokucloud; } });
Object.defineProperty(exports, "IchimokuCloud", { enumerable: true, get: function () { return IchimokuCloud_1.IchimokuCloud; } });
var KeltnerChannels_1 = require("./volatility/KeltnerChannels");
Object.defineProperty(exports, "keltnerchannels", { enumerable: true, get: function () { return KeltnerChannels_1.keltnerchannels; } });
Object.defineProperty(exports, "KeltnerChannels", { enumerable: true, get: function () { return KeltnerChannels_1.KeltnerChannels; } });
Object.defineProperty(exports, "KeltnerChannelsInput", { enumerable: true, get: function () { return KeltnerChannels_1.KeltnerChannelsInput; } });
Object.defineProperty(exports, "KeltnerChannelsOutput", { enumerable: true, get: function () { return KeltnerChannels_1.KeltnerChannelsOutput; } });
var ChandelierExit_1 = require("./volatility/ChandelierExit");
Object.defineProperty(exports, "chandelierexit", { enumerable: true, get: function () { return ChandelierExit_1.chandelierexit; } });
Object.defineProperty(exports, "ChandelierExit", { enumerable: true, get: function () { return ChandelierExit_1.ChandelierExit; } });
Object.defineProperty(exports, "ChandelierExitInput", { enumerable: true, get: function () { return ChandelierExit_1.ChandelierExitInput; } });
Object.defineProperty(exports, "ChandelierExitOutput", { enumerable: true, get: function () { return ChandelierExit_1.ChandelierExitOutput; } });
var Supertrend_1 = require("./volatility/Supertrend");
Object.defineProperty(exports, "supertrend", { enumerable: true, get: function () { return Supertrend_1.supertrend; } });
Object.defineProperty(exports, "Supertrend", { enumerable: true, get: function () { return Supertrend_1.Supertrend; } });
Object.defineProperty(exports, "SupertrendInput", { enumerable: true, get: function () { return Supertrend_1.SupertrendInput; } });
Object.defineProperty(exports, "SupertrendOutput", { enumerable: true, get: function () { return Supertrend_1.SupertrendOutput; } });
var CrossUp_1 = require("./Utils/CrossUp");
Object.defineProperty(exports, "crossUp", { enumerable: true, get: function () { return CrossUp_1.crossUp; } });
Object.defineProperty(exports, "CrossUp", { enumerable: true, get: function () { return CrossUp_1.CrossUp; } });
var CrossDown_1 = require("./Utils/CrossDown");
Object.defineProperty(exports, "crossDown", { enumerable: true, get: function () { return CrossDown_1.crossDown; } });
Object.defineProperty(exports, "CrossDown", { enumerable: true, get: function () { return CrossDown_1.CrossDown; } });
var config_1 = require("./config");
Object.defineProperty(exports, "setConfig", { enumerable: true, get: function () { return config_1.setConfig; } });
Object.defineProperty(exports, "getConfig", { enumerable: true, get: function () { return config_1.getConfig; } });
